server:
    port: 8081 # 设置服务端口
    servlet:
        contextPath: /demo  # 服务的路径  不写默认


logging:
  config: logback.xml # 日志的相关配置信息，都放在 `logback.xml` 文件中了
  level:
    com.maven.springboot.demo.control: trace # 指定具体的 mapper 中日志的输出级别，
    #上面的配置表示 `com.itcodai.course03.dao` 包下的所有 mapper 
    #日志输出级别为 trace，会将操作数据库的 sql 打印出来，开发时设置成 trace 方便定位问题，在生产环境上，将这个日志级别再设置成 error 级别即可

url:
  orderUrl: http://test.dyc.orderUrl.com
  userUrl: http://test.dyc.userUrl.com
  shopUrl: http://test.dyc.shopUrl.com
  masterUrl: http://test.dyc.masterUrl.com

swagger:
  enable: true



# 数据库地址
datasource:
  url: localhost:3306/menagerie

# mysql 数据库连接配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${datasource.url}?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&serverTimezone=UTC
    username: root
    password: 123456
    hikari: #springboot  自带连接池
      maximum-pool-size: 10  # 最大连接池数
      max-lifetime: 1770000


#
mybatis:
  type-aliases-package: com.maven.springboot.demo.entity
  configuration:
    map-underscore-to-camel-case: true # 驼峰命名规范
  mapper-locations: # mapper映射文件位置
    - classpath:mapper/*.xml